version: '3.8'

services:
  dashboard:
    image: ghcr.io/sladesouzasantos/shadow_simulator:latest
    command: streamlit run shadow_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8095:8501"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager] # Adicionado para consistência
    networks:
      - greencity-net

networks:
  greencity-net:
    external: true