version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8095:80"
    networks:
      - greencity-net

  dashboard:
    image: ghcr.io/${USER_GITHUB}/shadow-sim-pro:latest
    command: streamlit run shadow_app.py --server.port 8501 --server.address 0.0.0.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - greencity-net

networks:
  greencity-net:
    external: true